[package]
name = "rxrandr"
version = "0.1.0"
authors = ["Andy B. <brofi.archlinux@gmail.com>"]
edition = "2018"

[dependencies]
x11 = { version = "2.18.1", features = ["xlib", "xrandr"] }
gtk = { version = "0.8.0", features = ["embed-lgpl-docs"] }
gio = "0.8.0"
gdk = "0.12.0"
glib = "0.9.0"